function pointsXYZ = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  POINTSXYZ = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  POINTSXYZ = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  pointsXYZ = importfile("pointsXYZ.txt", [1, Inf]);
%
% Auto-generated by MATLAB on 23-Apr-2020 11:08:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Variable Properties
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Location Properties
opts.DataLines = dataLines; % Reads all rows of data between line 1 and
                            % the end of the file [1, Inf]
                            
% Delimited Text Properties
opts.Delimiter = " ";       
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Replacement Rules
opts.EmptyLineRule = "read";
opts.ExtraColumnsRule = "ignore";

% Import the data
pointsXYZ = readtable(filename, opts);

% Convert to homogeneous array
pointsXYZ = table2array(pointsXYZ);

end