function pointsXYZ = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  POINTSXYZ = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  POINTSXYZ = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  pointsXYZ = importfile("D:\¶Á²©À²\Research\Project\GitHub\CV_Proj\Proj2\Part 2 plane fit\pointsXYZ.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Apr-2020 11:08:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
pointsXYZ = readtable(filename, opts);

%% Convert to output type
pointsXYZ = table2array(pointsXYZ);
end